Epost-utsending ved (ny) bruker registrering og State endringer
mimir-org/typelibrary pull request #613
Opened 2023-06-07 12:19 UTC by kaihovden

Ved endring i et objekt sin 'state' sendes epost etter følgende regler:

- Draft - ingen epost utsendinger
- Approve - Da sendes epost til alle i selskapet som har 'Manage' og/eller 'Approve' rettigheter. Eposten sier at objektet trenger å bli 'Approved'.
- Approved - Da sendes epost til alle brukere som tidligere har satt objektet i 'Draft' og/eller 'Approve'. Det vil si at hvis en person oppretter objektet og en annen person klikker 'Approve' vil begge få en epost. Eposten sier at objektet nå er 'Approved'.
- Delete - Da sendes epost til alle i selskapet som har 'Manage' og/eller 'Delete' rettigheter. Eposten sier at objektet trenger å bli 'Deleted'.
- Deleted - Da sendes epost til alle brukere som tidligere har satt objektet i 'Draft' og/eller 'Delete'. Det vil si at hvis en person oppretter objektet og en annen person klikker 'Delete' vil begge få en epost. Eposten sier at objektet nå er 'Deleted'.

Hvis en (ny) bruker registrerer seg i Tyle:

- Det sendes en epost til selskapets 'Manager' om at en ny bruker er registrert. Eposten sier at denne brukeren trenger å få satt sin 'Access level'.

2023-06-07 12:59 UTC, jorgen-norheim requested changes

2023-06-07 12:59 UTC, jorgen-norheim commented on src/server/Mimirorg.Authentication/Repositories/MimirorgTemplateRepository.cs
> +                content = $"User {fromUser.FirstName} {fromUser.LastName} with email {fromUser.Email} request approval for the {objectTypeName} {objectName}. This can be done in Tyle under 'Settings'
requests

2023-06-07 12:59 UTC, jorgen-norheim commented on src/server/Mimirorg.Authentication/Repositories/MimirorgTemplateRepository.cs
> +                subject = $"Tyle {objectTypeName} is approved";
Bedre med has been her?

2023-06-07 12:59 UTC, jorgen-norheim commented on src/server/Mimirorg.Authentication/Repositories/MimirorgTemplateRepository.cs
> +                content = $"User {fromUser.FirstName} {fromUser.LastName} with email {fromUser.Email} request delete for the {objectTypeName} {objectName}. This can be done in Tyle under 'Settings' a
requests

2023-06-07 12:59 UTC, jorgen-norheim commented on src/server/Mimirorg.Authentication/Services/MimirorgUserService.cs
> +        var user = users.FirstOrDefault(x => x.Id == id);
Virker unødvendig å hente alle brukerne for så å filtrere, ville heller beholdt denne som den var.

2023-06-07 12:59 UTC, jorgen-norheim commented on src/server/Mimirorg.Authentication/Services/MimirorgUserService.cs
> +        }
Dette kan kanskje hentes ut til en egen metode? Så kan den også brukes over. I tillegg bør henting av alle selskap og permissions gjøres utenfor løkken.

2023-06-07 12:59 UTC, jorgen-norheim commented on src/server/TypeLibrary.Services/Services/EmailService.cs
> +            var companyDeleteAndManagers = allUsers.Where(x => x.CompanyId == currentUser.CompanyId && x.Permissions.ContainsValue(MimirorgPermission.Delete) || x.Permissions.ContainsValue(MimirorgPe
Her må approve være med, siden de også kan slette. Mulig det går an å bruke konseptet med flags her for å få til en slags større enn eller lik sammenligning på permissions.
I tillegg tror jeg logikken her ikke funker helt, at den foreksempel ikke vil sende epost til en bruker som har delete hos et selskap som ikke er brukerens "hovedselskap". Vet ikke hvordan syntaksen blir, men ser for meg noe sånt som dette istedet: x.Permissions.Contains((companyId, >= MimirorgPermission.Delete)).

2023-06-07 12:59 UTC, jorgen-norheim commented on src/server/Mimirorg.Authentication/Services/MimirorgUserService.cs
> +        var companyManagers = allUsers.Where(x => x.CompanyId == userCm.CompanyId && x.Permissions.ContainsValue(MimirorgPermission.Manage)).ToList();
Tror logikken her ikke stemmer helt, se kommentar lenger nede på det samme.

2023-06-07 12:59 UTC, jorgen-norheim commented on src/server/Mimirorg.Authentication/Services/MimirorgUserService.cs
> +            var email = await _templateRepository.CreateObjectStateEmail(sendToUser, fromUser, state, objectName, objectTypeName);
Litt usikker på om jeg forstår hvorfor denne metoden trengs. Er det ikke mulig å sende eposten direkte fra epost-servicen?

2023-06-07 13:02 UTC, kaihovden commented on src/server/Mimirorg.Authentication/Repositories/MimirorgTemplateRepository.cs
> +                content = $"User {fromUser.FirstName} {fromUser.LastName} with email {fromUser.Email} request approval for the {objectTypeName} {objectName}. This can be done in Tyle under 'Settings'
done

2023-06-08 06:29 UTC, kaihovden commented on src/server/Mimirorg.Authentication/Services/MimirorgUserService.cs
> +        var user = users.FirstOrDefault(x => x.Id == id);
Skal se på denne

2023-06-08 06:29 UTC, kaihovden commented on src/server/Mimirorg.Authentication/Services/MimirorgUserService.cs
> +        }
Enig. Kan flikke litt på den.

2023-06-08 07:03 UTC, kaihovden commented on src/server/TypeLibrary.Services/Services/EmailService.cs
> +            var companyDeleteAndManagers = allUsers.Where(x => x.CompanyId == currentUser.CompanyId && x.Permissions.ContainsValue(MimirorgPermission.Delete) || x.Permissions.ContainsValue(MimirorgPe
Ok, vi kan sende email til "alle" som har nødvendig permission (hasAccess)

2023-06-08 07:04 UTC, kaihovden commented on src/server/Mimirorg.Authentication/Services/MimirorgUserService.cs
> +        var companyManagers = allUsers.Where(x => x.CompanyId == userCm.CompanyId && x.Permissions.ContainsValue(MimirorgPermission.Manage)).ToList();
Relatert til den over, kan se på den når endring til 'hasPermissions' og at admin, mod og AM fpr epost.

2023-06-13 07:08 UTC, kaihovden commented on src/server/Mimirorg.Authentication/Services/MimirorgUserService.cs
> +        var companyManagers = allUsers.Where(x => x.CompanyId == userCm.CompanyId && x.Permissions.ContainsValue(MimirorgPermission.Manage)).ToList();
Denne skal være i orden nå.

2023-06-13 09:42 UTC, jorgen-norheim requested changes
Dette ser stort sett veldig fint ut! Det var bare en liten ting som jeg ikke tror funker helt som tenkt, se kommentar i koden. 🤓

2023-06-13 09:42 UTC, jorgen-norheim commented on src/server/Mimirorg.Authentication/Services/MimirorgUserService.cs
> +        var companyManagers = users.Where(x => x.Permissions.ContainsKey(user.CompanyId) && x.Permissions.ContainsValue(MimirorgPermission.Manage)).DistinctBy(x => x.Id).ToList();
Denne tror jeg ikke virker som tenkt. La oss si at en bruker registrerer seg hos selskapet "Selskap A". Da vil en bruker som har lesetilgang hos "Selskap A" og managerettigheter hos "Selskap B" få e-post.

2023-06-13 11:04 UTC, kaihovden commented on src/server/Mimirorg.Authentication/Services/MimirorgUserService.cs
> +        var companyManagers = users.Where(x => x.Permissions.ContainsKey(user.CompanyId) && x.Permissions.ContainsValue(MimirorgPermission.Manage)).DistinctBy(x => x.Id).ToList();
Tja, tanken er at denne linq spørringen skal sjekke at key OG value paret er riktig selskap OG permission. Men kanskje ikke den gjør det slik jeg tenker/tror. Skal sjekke opp i det.

2023-06-13 13:45 UTC, merged