Feature/added group attribute
mimir-org/typelibrary pull request #764
Opened 2023-09-08 13:07 UTC by AndyEPandy

Added Attribute group CRUD with new database tables.

2023-09-11 08:34 UTC, jorgen-norheim requested changes
Først av alt, mye bra arbeid. :) Ser du har skjønt strukturen og hvordan vi bygger opp ting. Noen generelle tilbakemeldinger under, ellers har jeg skrevet en del kommentarer i koden.

Migrations: Hvis vi ønsker å bruke denne i preprod-miljøet vårt uten å slette all data, så kan vi ikke "nullstille" migrations. Mulig å fikse dette uten å gjøre det?

Så vidt jeg kan se fins det ikke noen måte å se hvilke attributter som er koblet til et element via en gruppe. Det trengs ikke nødvendigvis å fikses nå, da vi kan ta det på en senere task.

2023-09-11 08:34 UTC, jorgen-norheim commented on src/server/Mimirorg.TypeLibrary/Models/Application/AttributeGroupLibAm.cs
> +        public int UserId { get; set; }
Denne blir aldri brukt til noe.

2023-09-11 08:34 UTC, jorgen-norheim commented on src/server/Mimirorg.TypeLibrary/Models/Client/AttributeGroupLibCm.cs
> +        public string TypeReference { get; set; }
Denne blir heller aldri brukt til noe, og virker ikke nødvendig å ha med.

2023-09-11 08:34 UTC, jorgen-norheim commented on src/server/TypeLibrary.Core/Controllers/V1/LibraryAttributeGroupController.cs
> +    private readonly IAttributeService _attributeService;
Blir aldri brukt.

2023-09-11 08:34 UTC, jorgen-norheim commented on src/server/TypeLibrary.Data/Contracts/IAttributeGroupRepository.cs
> +        /// <param name="createdBy">Used to set created by value for instances where objects are not created by the user</param>
Denne linja kan fjernes

2023-09-11 08:34 UTC, jorgen-norheim commented on src/server/TypeLibrary.Data/Repositories/Ef/EfAttributeGroupRepository.cs
> +        public async Task ChangeState(string id, State state, bool sendStateEmail)
Kan fjernes

2023-09-11 08:34 UTC, jorgen-norheim commented on src/server/TypeLibrary.Data/Repositories/Ef/EfAttributeGroupRepository.cs
> +            //BUG: TODO if list is null it fails
Bør helst fikses. Du kan for eksempel initialisere en tom liste når dm-en lages?

2023-09-11 08:34 UTC, jorgen-norheim commented on src/server/TypeLibrary.Data/Repositories/Ef/EfAttributeGroupRepository.cs
> +        public AttributeGroupLibDm Update(string id, AttributeGroupLibDm attributeGroupLibDm)
Denne kan vel også fjernes, ihvertfall slik som koden er nå.

2023-09-11 08:34 UTC, jorgen-norheim commented on src/server/TypeLibrary.Services/Services/AttributeGroupService.cs
> +        private readonly ILogService _logService;
Brukes aldri

2023-09-11 08:34 UTC, jorgen-norheim commented on src/server/TypeLibrary.Services/Services/AttributeGroupService.cs
> +        IEnumerable<AttributeGroupLibCm> IAttributeGroupService.GetAttributeGroupList()
Her har du en form for dobbel implementasjon av samme metode

2023-09-11 08:34 UTC, jorgen-norheim commented on src/server/TypeLibrary.Services/Services/AttributeGroupService.cs
> +                throw new MimirorgBadRequestException("Attribute is not valid.", validation);
Her bør det stå Attribute group

2023-09-11 08:34 UTC, jorgen-norheim commented on src/server/TypeLibrary.Services/Services/AttributeGroupService.cs
> +        public async Task<AttributeGroupLibCm> Update(string id, AttributeGroupLibAm attributeAm)
Ved å gjøre det på denne måten så vil gruppen få en ny id, og da knekker alle gamle referanser. Så det bør nok implementeres en "ordentlig" update-metode.

2023-09-11 08:34 UTC, jorgen-norheim commented on src/server/Mimirorg.TypeLibrary/Models/Client/AttributeGroupLibCm.cs
> +    }
Det mangler en liste over attributtene i gruppa.

2023-09-11 08:34 UTC, jorgen-norheim commented on src/server/TypeLibrary.Core/Controllers/V1/LibraryAttributeGroupController.cs
> +            _logger.LogError("Internal server error", (e.Message, e.StackTrace, e.InnerException, e.Data, e.Source));
Denne log-statementen virker nok ikke helst som intended (kun internal server error som blir logget).

2023-09-11 14:50 UTC, AndyEPandy commented on src/server/Mimirorg.TypeLibrary/Models/Client/AttributeGroupLibCm.cs
> +        public string TypeReference { get; set; }
Enig. Jeg var usikker i starten hva det var men ser at den ikke trengs. Fjerner den og mappingen (som er Ignore).

2023-09-11 14:51 UTC, AndyEPandy commented on src/server/TypeLibrary.Core/Controllers/V1/LibraryAttributeGroupController.cs
> +    private readonly IAttributeService _attributeService;
Det er sant. Jeg fjerner.

2023-09-11 14:55 UTC, AndyEPandy commented on src/server/TypeLibrary.Core/Controllers/V1/LibraryAttributeGroupController.cs
> +    /// Delete an attribute goup that is not approved
Fikset.

2023-09-11 14:55 UTC, AndyEPandy commented on src/server/TypeLibrary.Core/Profiles/AttributeGroupProfile.cs
> +            CreateMap<AttributeGroupLibCm, ApprovalCm>()
Fjernet

2023-09-11 14:59 UTC, AndyEPandy commented on src/server/TypeLibrary.Services/Services/AttributeGroupService.cs
> +                throw new MimirorgBadRequestException("Attribute is not valid.", validation);
Ja , enig. Det er bedre lesbart.

2023-09-11 15:01 UTC, AndyEPandy commented on src/server/Mimirorg.TypeLibrary/Models/Client/AttributeGroupLibCm.cs
> +    }
Ja det ser jeg nå. Jeg ser på andre controllere og at klienten vil ha tilbake denne infoen. Jeg fikser det.

2023-09-12 16:13 UTC, AndyEPandy commented on src/server/TypeLibrary.Services/Services/AttributeGroupService.cs
> +        IEnumerable<AttributeGroupLibCm> IAttributeGroupService.GetAttributeGroupList()
Ja. Den som ikke er i bruk er fjernet.

2023-09-13 06:44 UTC, AndyEPandy commented on src/server/TypeLibrary.Core/Controllers/V1/LibraryAttributeGroupController.cs
> +            _logger.LogError("Internal server error", (e.Message, e.StackTrace, e.InnerException, e.Data, e.Source));
Det er korrekt. Jeg gjør logging lik som Block controller så ser vi på logging generelt på et senere tidspunkt

2023-09-13 13:02 UTC, AndyEPandy commented on src/server/TypeLibrary.Services/Services/AttributeGroupService.cs
> +        public async Task<AttributeGroupLibCm> Update(string id, AttributeGroupLibAm attributeAm)
Denne metoden er nå endret og knekker ikke referanser som blokker vil ha.

2023-09-14 08:47 UTC, jorgen-norheim requested changes
Fremdeles noe kode som bør fjernes og noen andre småting.

2023-09-14 08:47 UTC, jorgen-norheim commented on src/server/TypeLibrary.Core/Profiles/AttributeGroupProfile.cs
> +            //.ForMember(dest => dest.Attributes, opt => opt.MapFrom(src => src.Attributes))
Bør fjernes?

2023-09-14 08:47 UTC, jorgen-norheim commented on src/server/TypeLibrary.Core/Profiles/AttributeGroupProfile.cs
> +            CreateMap<AttributeGroupLibCm, ApprovalCm>()
Den er vel her fremdeles?

2023-09-14 08:47 UTC, jorgen-norheim commented on src/server/TypeLibrary.Data/Repositories/Ef/EfAttributeGroupRepository.cs
> +        public async Task ChangeState(string id, State state, bool sendStateEmail)
Ikke fjernet

2023-09-14 08:47 UTC, jorgen-norheim commented on src/server/TypeLibrary.Data/Repositories/Ef/EfAttributeGroupRepository.cs
> +            //BUG: TODO if list is null it fails
Syns fremdeles denne skal fikses, med mindre den er fikset. I så fall bør kommentaren fjernes.

2023-09-14 08:47 UTC, jorgen-norheim commented on src/server/TypeLibrary.Data/Repositories/Ef/EfAttributeGroupRepository.cs
> +        public AttributeGroupLibDm Update(string id, AttributeGroupLibDm attributeGroupLibDm)
Denne er fremdeles ikke i bruk og bør fjernes

2023-09-14 08:47 UTC, jorgen-norheim commented on src/server/TypeLibrary.Data/Contracts/IAttributeGroupRepository.cs
> +        /// <param name="createdBy">Used to set created by value for instances where objects are not created by the user</param>
Kan fremdeles fjernes

2023-09-14 08:47 UTC, jorgen-norheim commented on src/server/TypeLibrary.Data/Contracts/IAttributeGroupRepository.cs
> +        Task<AttributeGroupLibDm> Create(AttributeGroupLibDm attributeAm);
Gjelder fremdeles

2023-09-14 08:47 UTC, jorgen-norheim commented on src/server/TypeLibrary.Data/Contracts/IAttributeGroupRepository.cs
> +        AttributeGroupLibDm Update(string id, AttributeGroupLibDm attributeAm);
Gjelder også fremdeles

2023-09-14 08:47 UTC, jorgen-norheim commented on src/server/TypeLibrary.Data/Contracts/IAttributeGroupRepository.cs
> +        Task ChangeState(string id, State state, bool sendStateEmail);
Gjelder fremdeles

2023-09-14 08:47 UTC, jorgen-norheim commented on src/server/TypeLibrary.Services/Services/AttributeGroupService.cs
> +        private readonly ILogService _logService;
Gjelder fremdeles. Kanskje den bør brukes?

2023-09-14 08:52 UTC, AndyEPandy commented on src/server/TypeLibrary.Core/Profiles/AttributeGroupProfile.cs
> +            //.ForMember(dest => dest.Attributes, opt => opt.MapFrom(src => src.Attributes))
Ja. Fjernet.

2023-09-15 09:07 UTC, jorgen-norheim approved these changes
👍

2023-09-15 09:07 UTC, merged