Feature/add attribute group frontend
mimir-org/typelibrary pull request #786
Opened 2023-09-29 09:11 UTC by AndyEPandy

2023-09-29 10:48 UTC, mrboen94 requested changes
Backenden får Jørgen gå over då han har beire oversikt over denne.

Ellers er her mykje bra arbeid!

![Way To Go Yes GIF by Dirty Bandits](https://media0.giphy.com/media/kigLtfDrV3K9N0wYCO/200.gif)

2023-09-29 10:48 UTC, mrboen94 commented on src/client/src/features/entities/attributeGroups/AttributeGroupForm.tsx
> +            <AttributeGroupFormBaseFields mode={mode} />
Sia denne er litt vanskelig å lese (dette gjeld alle formsa som er i bruk i dag, så kan ein gjerne flytte denne koden ut:

```tsx
const AttributeGroupFormContent = ({ mode, register, fields, append, remove }) => {
  const theme = useTheme();
  return (
    <>
      <AttributeGroupFormBaseFields mode={mode} />
      <Box display={"flex"} flex={3} flexDirection={"column"} gap={theme.mimirorg.spacing.multiple(6)}>
        <FormAttributes register={(index) => register(`attributes.${index}`)} fields={fields} append={append} remove={remove} preprocess={prepareAttributes} />
      </Box>
    </>
  );
};
```

Det er nok ikkje nødvendig å flytte dette til ei separat fil, men å berre flytte denne delen ut av koden vil gjere den enklare å lese.

(Ikkje nødvendig, berre en kommentar)

2023-09-29 10:48 UTC, mrboen94 commented on src/client/src/features/entities/attributeGroups/AttributeGroupForm.tsx
> +
Legg gjerne til litt jsdoc for komponenten, slik at du får dokumentasjon frå IDEen når du arbeider i andre filer.

2023-09-29 10:48 UTC, mrboen94 commented on src/client/src/features/entities/attributeGroups/types/formAttributeGroupLib.ts
> + * This type functions as a layer between client needs and the backend model.
Veit ikkje om dette er gyldig jsdoc, så legg gjerne til noken tags om det ikkje er det.

2023-09-29 10:48 UTC, mrboen94 commented on src/client/src/features/entities/attributes/types/formAttributeLib.ts
> +export const toFormAttributeHelper = (unit: AttributeLibCm): FormAttributeHelper => {
Skal denne funksjonen ligge i types mappa?

Burde vel kanskje ligge i ei lib mappe? Veit ikkje om der er fleire av desse filene i denne mappa, og ser ikkje heile fila her no, men ser for meg at denne funksjonen burde ligge en anna plass. Det må du avgjere litt sjøl.

2023-09-29 10:48 UTC, mrboen94 commented on src/client/src/features/entities/common/form-attributeGroup/FormAttributeGroups.helpers.tsx
> +export const onAddAttributeGroup = (
Trur denne er for avansert, kul implementasjon, men meina ReactSelect har dette innebygd, eg kan sjå litt på det ilag med deg for å sjå om denne funksjonen gjer det eg trur den gjer.

2023-09-29 10:48 UTC, mrboen94 commented on src/client/src/features/entities/common/form-attributeGroup/FormAttributeGroups.tsx
> +  //Add get attributes also for each group? If above is not sufficent ie name
Føle ikkje at denne kommentaren gjer meg så mykje meir informasjon, så den kan kanskje slettast :D

2023-09-29 10:48 UTC, mrboen94 commented on src/client/src/features/entities/entityPreviews/attributeGroup/AttributeGroupFormPreview.tsx
> +  //  const units = useWatch({ control, name: "units" });
Delete

2023-09-29 10:48 UTC, mrboen94 commented on src/client/src/features/entities/entityPreviews/attributeGroup/AttributeGroupFormPreview.tsx
> +        // units={units}
Delete

2023-09-29 10:48 UTC, mrboen94 commented on src/client/src/features/entities/entityPreviews/attributeGroup/AttributeGroupFormPreview.tsx
> +        name={name ? name : t("attributeGroup.name")}
name ?? t("attributeGroup.name")

2023-09-29 10:48 UTC, mrboen94 commented on src/client/src/features/entities/terminal/TerminalForm.tsx
> +                // preprocess={prepareAttributeGroups}
Delete

2023-09-29 10:48 UTC, mrboen94 commented on src/client/src/features/entities/types/FormAttributeHelper.ts
> +export interface FormAttributeHelper {
Legg gjerne til jsDoc til interfaces, på den måten får vi meir hjelp i IDEen.

2023-09-29 10:48 UTC, mrboen94 commented on src/client/src/features/explore/search/components/SearchItemActions.helpers.ts
> +  const patchAttributeGroup = usePatchAttributeState(); //This is just to fix dependencies as attribute group does not have state.... It will never be called...
Forklar denne til meg, skjønna ikkje heilt ka du meina.

2023-09-29 10:48 UTC, mrboen94 commented on src/client/src/locales/en/entities.json
> +
Kan hende det er github som klikka her, men formatteringa bør vere riktig (i følge github har du lagt til linjeskift her
![image](https://github.com/mimir-org/typelibrary/assets/24441871/cf81f18f-e1eb-43f4-9558-345de0e88858)

2023-09-29 10:48 UTC, mrboen94 commented on src/server/Mimirorg.TypeLibrary/Models/Client/AttributeGroupLibCm.cs
> +
Kan vere git, men ser ut som du har lagt til space igjen?

2023-09-29 11:17 UTC, AndyEPandy commented on src/client/src/external/sources/attributeGroup/attributeGroup.api.ts
> +  putAttributeGroup(item: AttributeGroupLibAm, id?: string) {
Nei, AttributeGroupLibAm har ikke Id på seg. Det burde den kanske hatt men for standardiseringens del så foreslår jeg å beholde den slik den er.

2023-09-29 11:43 UTC, jorgen-norheim requested changes

2023-09-29 11:43 UTC, jorgen-norheim commented on src/client/src/features/entities/attributeGroups/AttributeGroupFormRoutes.tsx
> +export const attributeGroupFormBasePath = "form/attributeGroup";
Foreslår lowercase her også, med mindre vi har camelcase i andre url-er?

2023-09-29 11:43 UTC, jorgen-norheim commented on src/server/TypeLibrary.Core/Migrations/TypeLibraryDbContextModelSnapshot.cs
> +                        .HasColumnType("nvarchar(max)");
Nvarchar(max) bør vi unngå, sett en grense for denne verdien i config

2023-09-29 12:20 UTC, AndyEPandy commented on src/client/src/external/sources/attributeGroup/attributeGroup.api.ts
> +    return apiClient.get<AttributeGroupLibCm>(`${_basePath}/${id}`).then((r) => r.data);
Bør sees på men holder den lik som for andre api kall.

2023-09-29 12:21 UTC, AndyEPandy commented on src/client/src/external/sources/attributeGroup/attributeGroup.queries.ts
> +// export const usePatchAttributeState = () => {
Done

2023-09-29 12:21 UTC, AndyEPandy commented on src/client/src/features/entities/terminal/TerminalForm.tsx
> +                // preprocess={prepareAttributeGroups}
Done

2023-09-29 12:26 UTC, AndyEPandy commented on src/client/src/features/entities/types/FormAttributeHelper.ts
> +export interface FormAttributeHelper {
Done

2023-09-29 12:26 UTC, AndyEPandy commented on src/client/src/features/explore/search/components/SearchItemActions.helpers.ts
> +  const patchAttributeGroup = usePatchAttributeState(); //This is just to fix dependencies as attribute group does not have state.... It will never be called...
Denne har vi sett på.

2023-09-29 12:30 UTC, AndyEPandy commented on src/client/src/common/utils/mappers/mapAttributeGroupLibCmToInfoItem.tsx
> +  //   const attributeHasUnits = attribute.attributeGroupUnits && attribute.attributeGroupUnits.length > 0;
Done

2023-09-29 12:32 UTC, AndyEPandy commented on src/server/Mimirorg.TypeLibrary/Models/Client/AttributeGroupLibCm.cs
> +
Idk. Fikset i alle fall

2023-09-29 12:34 UTC, AndyEPandy commented on src/client/src/common/utils/mappers/mapAttributeGroupLibCmToInfoItem.tsx
> +  if (true) {
Fjernet. Noe som har vært testet her men glemt å slette

2023-09-29 13:28 UTC, AndyEPandy commented on src/client/src/features/entities/attributeGroups/AttributeGroupFormRoutes.tsx
> +export const attributeGroupFormBasePath = "form/attributeGroup";
Fortsetter med lower case. Jeg har kun funnet endepunkter med ett ord (block, terminal etc.) så jeg vet faktisk ikke hva som er vanlig.

2023-10-02 06:46 UTC, AndyEPandy commented on src/server/TypeLibrary.Core/Migrations/TypeLibraryDbContextModelSnapshot.cs
> +                        .HasColumnType("nvarchar(max)");
Fikset

2023-10-02 07:38 UTC, jorgen-norheim approved these changes
Supert :)

2023-10-02 08:07 UTC, Bouvet-MatsAlmeland reviewed
Ser bra ut. Har kun et spm.

2023-10-02 08:07 UTC, Bouvet-MatsAlmeland commented on src/client/src/features/explore/about/components/attributeGroup/AttributeGroupPanel.tsx
> + * Component that displays information about a given terminal.
Er det snakk om terminal her, eller atributtgrupper?

2023-10-02 08:55 UTC, jorgen-norheim approved these changes
Ser fint ut

2023-10-02 09:06 UTC, AndyEPandy commented on src/client/src/features/explore/about/components/attributeGroup/AttributeGroupPanel.tsx
> + * Component that displays information about a given terminal.
Fixa

2023-10-02 09:50 UTC, merged